#!/bin/bash

# by default, tile all windows
yabai -m config layout bsp

yabai -m config split_type auto

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

yabai -m rule --add app="^System Settings$" layer=above manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

yabai -m rule --add app="^Alacritty$" space=^1

yabai -m rule --add app="^Ueli$" manage=off
yabai -m rule --add app="^Ueli$" float=on

# yabai -m config external_bar all:32:0

borders active_color=0xff8aadf4 inactive_color=0xff181926 width=10.0 &
